config/routes.rb
Rails.application.routes.draw do
  resources :links
  resources :views, path: :v, only: [:show]

  root "links#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/base62.rb
class Base62
  ALPHABET = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ".freeze
  BASE = ALPHABET.length
  def self.encode(number)
    return ALPHABET.first if number.zero? || number.nil?

    result = ""

    while number > 0 do
      index = number % BASE
      char = ALPHABET[index]
      result.prepend char
      number /= BASE
    end

    result
  end

  def self.decode(string)
    number = 0

    string.reverse.each_char.with_index do |char, index|
      power = BASE**index
      index = ALPHABET.index(char)
      number += index * power
    end

    number
  end
end

app/models/link.rb
class Link < ApplicationRecord
  has_many :views, dependent: :destroy
  scope :recent_first, -> { order(created_at: :desc) }

  validates :url, presence: true

  after_save_commit if: :url_previously_changed? do
    MetadataJob.perform(to_param)
  end

  def self.find(id)
    super Base62.decode(id)
  end

  def to_param
    Base62.encode(id)
  end

  def domain
    URI(url).host
  rescue URI::InvalidURIError

  end
end

app/models/metadata.rb
require "open_uri"
class Metadata
  attr_reader :doc
  def self.retrieve_from(url)
    new(URI.open(url))
  rescue StandardError
    new
  end

  def initialize(html)
    @doc = Nokogiri::HTML(html)
  end

  def attributes
    {
      title: title,
      description: description,
      image: image
    }
  end

  def title
    meta_tag_content "title"
  end

  def description
    meta_tag_content "description"
  end

  def image
    meta_tag_content "og:image", name_attribute: :property
  end

  def meta_tag_content(name, name_attribute: :name)
    doc.at_css("meta[property='#{name}']")&.attributes&.fetch("content", nil)&.text
  end
end

app/models/view.rb
class View < ApplicationRecord
  belongs_to :link, counter_cache: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  def set_link
    @link = Link.find(params[:id])
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]
  def index
    @links = Link.recent_first
    @link ||= Link.new
  end

  def show

  end

  def create
    @link = Link.new(link_params)
    if @link.save
      redirect_to root_path
    else
      index
      render :index, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @link.update(link_params)
      redirect_to @link
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @link.destroy
    redirect_to root_path, notice: "Suppression effectuée"
  end

  private

  def link_params
    params.require(:link).permit(:url)
  end
end

app/controllers/views_controller.rb
class ViewsController < ApplicationController
  before_action :set_link

  rescue_from ActiveRecord::RecordNotFound do
    redirect_to root_path
  end
  def show
    @link.views.create(ip: request.ip, user_agent: request.user_agent)
    redirect_to @link.url, allow_other_host: true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favicon_helper.rb
module FaviconHelper
  def favicon_image_tag(domain, **kwargs)
    image_tag google_favicon_url(domain), **kwargs
  end
  def google_favicon_url(domain)
    "https://www.google.com/s2/favicons?domain=#{domain}"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Url Shortener" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <script src="https://unpkg.com/popper.js@1"></script>
    <script src="https://unpkg.com/tippy.js@5"></script>
    <script src="https://unpkg.com/popper.js@1"></script>
    <script src="https://unpkg.com/tippy.js@5/dist/tippy-bundle.iife.js"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="prose mx-auto mt-28 px-5">
      <% if alert %>
        <p class="bg-pink-100 text-pink-400 rounded"><%= alert %></p>
      <% end %>
      <% if notice %>
        <p class="bg-pink-50 text-pink-400 rounded"><%= notice %></p>
      <% end %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/links/_form.html.erb
<%= form_with model: @link do |form| %>
  <div class="flex gap-2 items-center">
    <%= form.url_field :url, autofocus: true, placeholder: "https://exemple.com", class: "flex-grow rounded" %>
    <%= form.submit "Sauvegarder", class: "px-3 py-2 bg-pink-50 rounded" %>
  </div>

<% end %>

app/views/links/_link.html.erb
<%= tag.div id: dom_id(link) do %>
  <%= turbo_stream_from link %>

  <div class="grid grid-cols-8 py-4 items-center">

    <div class="col-span-4">
      <%= link_to view_path(link), target: :_blank, data: {turbo: false} do %>
        <%= favicon_image_tag link.domain, class: "inline-block m-0" %>
        <%= link.title || link.url %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="inline-block size-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M13.5 6H5.25A2.25 2.25 0 0 0 3 8.25v10.5A2.25 2.25 0 0 0 5.25 21h10.5A2.25 2.25 0 0 0 18 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25" />
        </svg>
      <% end %>
    </div>


    <div class="col-span-2 text-center text-xs text-right">
      <%= link_to pluralize(link.views_count, "vue"), link, class: "px-3 py-1.5 rounded bg-pink-50 no-underline" %>
    </div>

    <div class="text-center text-xs text-right">
      <%= button_tag "Copier", class: "px-3 py-1.5 rounded bg-pink-50 no-underline", data: {controller: "clipboard", clipboard_text: view_url(link)} %>
    </div>



  </div>


<% end %>

app/views/links/edit.html.erb
<h1>Modification d'un lien</h1>

<%= render partial: "form", local: {link: @link} %>

<div class="flex gap-2 items-center">
  <%= link_to "Annuler", @link %>
  ou
  <%= button_to "Supprimer", @link, method: :delete, data: { turbo_confirm: "Êtes vous sûr ?"} %>
</div>

app/views/links/index.html.erb
<h1>URL Shortener !</h1>

<%= render partial: "form", locals: {link: @link} %>

<div class="mt-4 flex flex-col divide-y divide-pink-100">
  <%= render @links %>
</div>

app/views/links/show.html.erb
<div class="flex justify-between items-center text-xs">
  <%= link_to "← Retour", root_path, class: "no-underline text-xs text-pink-400 px-3 py-2 rounded bg-pink-50" %>
  <div class="flex items-center gap-4">
    <%= tag.div pluralize(@link.views_count, "vue") %>
    <%= link_to "Modifier", edit_link_path(@link), class: "px-3 py-1.5 rounded bg-pink-50 no-underline"  %>
  </div>
</div>


<h1 class="mt-4"><%= @link.url %></h1>
<%= @link.description %>

<div class="=text-xs flex justify-between items-center">
  <%= link_to view_path(@link), target: :_blank, data: {turbo: false}, class: "no-underline text-xs px-3 py-1.5 rounded bg-pink-50 no-underline" do %>
    <%= favicon_image_tag @link.domain, class: "inline-block" %>
    <%= @link.url %>
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="inline-block size-5">
      <path stroke-linecap="round" stroke-linejoin="round" d="M13.5 6H5.25A2.25 2.25 0 0 0 3 8.25v10.5A2.25 2.25 0 0 0 5.25 21h10.5A2.25 2.25 0 0 0 18 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25" />
    </svg>
  <% end %>
</div>

<%= line_chart @link.views.group_by_day(:created_at, range: 2.weeks.ago..Time.now, expand_range: true).count %>